Adaptive
korotkir/travel_across_russia pull request #4
Opened 2021-09-06 19:55 UTC by tre3ubec

2021-09-06 19:57 UTC, tre3ubec commented on index.html
> +            <div class="place__website">
Не стал убирать place__website, на митинге объясню по какой причине.

2021-09-06 19:59 UTC, tre3ubec commented on style/style.scss
> +@media (max-width: 660px) {
max-width не 320 чтобы на всех разрешениях более менее норм отображалось, но верстка по 320 шаблону

2021-09-08 17:27 UTC, dimichisoradev requested changes
Ты очень большой молодец! Адаптивка - зачет. Была проделана колосальная работа. Костылей нету. Я максимально доволен.
Хорошо было бы избавиться от vw и при стягивании растягивании экрана у тебя всплывает анимация странная увеличения <=> уменьшения, было бы хорошо избавиться от неё 
![image](https://user-images.githubusercontent.com/89395222/132556247-79bcd4ba-4457-4a93-8343-c0f93090b8d1.png)

ПС (с твоим уровнем знаний и понимания темы, хорошо бы сделать респонсивку), если этот макет задолбал, давай найду другой, что бы простоя не было. Леше еще догонять.

2021-09-08 17:27 UTC, dimichisoradev commented on index.html
> +    <div class="header__langLinks">
Это список

2021-09-08 17:27 UTC, dimichisoradev commented on index.html
> +            <div class="place__website">
Нормально, можешь оставлять, я хотел предложить просто более скиллово сделать всё

2021-09-08 17:27 UTC, dimichisoradev commented on index.html
> +        <a class="header__langLink header__langLink_active" href="#">Ru</a>
header__langLink_active сделай через border-bottom (доп задание)

2021-09-08 17:27 UTC, dimichisoradev commented on index.html
Тут два параграфа, не абузь вайтспейс

2021-09-08 17:27 UTC, dimichisoradev commented on index.html
>      <div class="lead">
`<section>`

2021-09-08 17:27 UTC, dimichisoradev commented on index.html
>          <h1 class="lead__title">Путешествия
Для заголовков лучше использовать не вайтспейс

2021-09-08 17:27 UTC, dimichisoradev commented on index.html
> +    <a href="#"><img class="header__logo" src="img/logo.svg" alt="Россия"></a>
`<a>` тоже элемент, хорошо бы это было обозначить

2021-09-08 17:27 UTC, dimichisoradev commented on index.html
>  по России</h1>
`<h3>` тут не актуален, нужно использовать `<p>`
https://www.w3.org/TR/2014/REC-html5-20141028/common-idioms.html
ссылка на стандарт, если не поверишь

2021-09-08 17:27 UTC, dimichisoradev commented on index.html
> -                <h2 class="place__title">Куршская
Переносить слова в заголовке лучше не вайтспейсом, а еще можно придумать как это сделать без того и другого

2021-09-08 17:27 UTC, dimichisoradev commented on index.html
>      </div>
В списке `<li>` какие то очень тонкие, посмотри в девтулзах. Исправлять не обязательно

2021-09-08 17:27 UTC, dimichisoradev commented on index.html
>          <div class="cover">
cursor: pointer

2021-09-08 17:27 UTC, dimichisoradev commented on style/style.css
>  }
body - это вполне себе блок и может иметь в себе селектор

2021-09-08 17:27 UTC, dimichisoradev commented on index.html
> +<footer class="footer">
![image](https://user-images.githubusercontent.com/89395222/132555314-00ceed65-d20c-40a2-aa5a-a8ecde244de7.png)
На 1024 скакнул

2021-09-12 10:11 UTC, merged